In [6]:
path= "shopping-natalizio-5000.csv"
path

'shopping-natalizio-5000.csv'

In [8]:
# after loading dataset using pandas to read it
import pandas as pd

In [15]:
s= pd.read_csv(path)
s

,customer_id,age,primary_category,device_type,average_basket_value,purchases_per_month,time_on_site_minutes,discount_sensitivity,loyalty_program_member,holiday_purchase_likelihood,estimated_holiday_spending
0,221958,68,Electronics,Mobile,520.442026,7,7.6,0.219270,0,0,480.257323
1,771155,39,Beauty,Mobile,235.010000,1,13.4,0.000000,1,0,112.062036
2,231932,64,Beauty,Mobile,78.730000,2,22.9,0.244672,0,0,281.626797
3,465838,21,Sporting Goods,Desktop,139.590000,8,21.8,0.906165,1,0,1176.353803
4,359178,45,Books,Tablet,121.480000,1,6.6,0.355770,0,0,9.362103
...,...,...,...,...,...,...,...,...,...,...,...
4995,618823,29,Toys,Desktop,112.610000,4,28.6,0.768483,1,0,701.913076
4996,319526,30,Beauty,Mobile,141.730000,2,0.6,0.676469,1,0,472.090089
4997,998662,62,Electronics,Mobile,261.987274,9,22.2,0.270172,0,0,148.546640
4998,447220,59,Toys,Tablet,71.720000,5,21.5,0.062861,0,0,222.072073
4999,924834,56,Clothing,Desktop,62.930000,3,10.8,0.693081,1,0,403.779552

In [21]:
# summary of dataset
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  5000 non-null   int64
 1   age                          5000 non-null   int64
 2   primary_category             5000 non-null   object
 3   device_type                  5000 non-null   object
 4   average_basket_value         5000 non-null   float64
 5   purchases_per_month          5000 non-null   int64
 6   time_on_site_minutes         5000 non-null   float64
 7   discount_sensitivity         5000 non-null   float64
 8   loyalty_program_member       5000 non-null   int64
 9   holiday_purchase_likelihood  5000 non-null   int64
 10  estimated_holiday_spending   5000 non-null   float64
dtypes: float64(4), int64(5), object(2)
memory usage: 429.8+ KB

In [22]:
s.

NameError: name 'c' is not defined

In [19]:
#statastical summary of dataset
s.describe()

,customer_id,age,average_basket_value,purchases_per_month,time_on_site_minutes,discount_sensitivity,loyalty_program_member,holiday_purchase_likelihood,estimated_holiday_spending
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,551628.123800,43.418000,137.873161,5.016600,15.073520,0.499614,0.396000,0.150200,301.013636
std,260310.782449,14.977748,99.336623,2.555158,10.080299,0.286339,0.489113,0.357303,372.136981
min,100126.000000,18.000000,-48.260000,1.000000,-19.400000,0.000000,0.000000,0.000000,-1598.842340
25%,320778.500000,31.000000,88.850000,3.000000,8.300000,0.274457,0.000000,0.000000,68.489263
50%,554853.500000,43.000000,123.520000,5.000000,14.900000,0.500017,0.000000,0.000000,264.169654
75%,777125.500000,56.000000,161.845000,7.000000,21.800000,0.720851,1.000000,0.000000,501.379565
max,999885.000000,69.000000,1251.534342,9.000000,53.100000,1.000000,1.000000,1.000000,2135.586374

In [24]:
s['primary_category']

0          Electronics
1               Beauty
2               Beauty
3       Sporting Goods
4                Books
             ...
4995              Toys
4996            Beauty
4997       Electronics
4998              Toys
4999          Clothing
Name: primary_category, Length: 5000, dtype: object



>**1.['estimated_holiday_spending'] (Bracket notation):**
Accesses a column/key using its exact name as a string
Works always, even if:
1.Column name has spaces ("holiday spending")
2.Column name has special characters ($, -, etc.)
3.Column name conflicts with existing methods


**2. s.estimated_holiday_spending (Dot notation)**
Accesses column like an attribute
Works only if:
Name has no spaces or special characters
Name does not conflict with built-in attributes/methods

In [28]:

s['estimated_holiday_spending']

0        480.257323
1        112.062036
2        281.626797
3       1176.353803
4          9.362103
           ...
4995     701.913076
4996     472.090089
4997     148.546640
4998     222.072073
4999     403.779552
Name: estimated_holiday_spending, Length: 5000, dtype: float64

In [27]:
s.estimated_holiday_spending

0        480.257323
1        112.062036
2        281.626797
3       1176.353803
4          9.362103
           ...
4995     701.913076
4996     472.090089
4997     148.546640
4998     222.072073
4999     403.779552
Name: estimated_holiday_spending, Length: 5000, dtype: float64

In [29]:
s['primary_category'].unique()

array(['Electronics', 'Beauty', 'Sporting Goods', 'Books', 'Clothing',
       'Toys', 'Home & Kitchen'], dtype=object)

In [31]:
s.primary_category.unique()

array(['Electronics', 'Beauty', 'Sporting Goods', 'Books', 'Clothing',
       'Toys', 'Home & Kitchen'], dtype=object)

In [33]:
#here we calculate frequency of purchasing categories
s['primary_category'].value_counts()

primary_category
Electronics       742
Toys              736
Sporting Goods    728
Clothing          715
Home & Kitchen    706
Books             699
Beauty            674
Name: count, dtype: int64

methods that learned:
1. info (to get summary)
2. describe (to get statastical summary
3. unique (returns unique values)
4. value_count ( returns unique values with thier freq)